<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findSuggestions($q, $maxType)
    {
        $query = 'SELECT p FROM AppBundle:Place p' .
            ' WHERE LOWER(p.name) LIKE :q';
        if(isset($maxType)) {
            $query .= ' AND p.type<=:maxType';
        }
        $qObject = $this->getEntityManager()->createQuery(
            $query
        )->setParameter("q", strtolower($q) . '%');
        if(isset($maxType)) {
            $qObject->setParameter("maxType", $maxType);
        }
        return $qObject
            ->getResult();

    }
}
